appOutletCar/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from rest_framework import routers

from django.contrib.auth.decorators import login_required
from rest_framework.urlpatterns import format_suffix_patterns
app_name='appOutletCar'
router = routers.SimpleRouter()
urlpatterns = [
    path('cochess', views.CocheList.as_view(), name='cochess'),
    path('cochess/<int:pk>/', views.CocheDetail.as_view()),
    path('', views.HomePageView.as_view(), name='home'),
    path('postAjax/<int:coche_id>/', views.ajax, name='ajax'),
    path('listaCochesNuevos', views.listaCochesNuevos.as_view(), name='listaCochesNuevos'),
    path('listaCochesSegunda', views.listaCochesSegunda.as_view(), name='listaCochesSegunda'),
    path('listaCocheskm0', views.listaCochesKm0.as_view(), name='listaCocheskm0'),

    path('detalle_coche/<int:coche_id>/', views.DetailViewCoches, name='detail'),
    path('', views.CocheCreateView.as_view(), name='cocheCreateView'),
    url('añadirCoche', views.añadirCoche, name='añadirCoche'),
    
    path('nuestrasMarcas', views.nuestrasMarcas.as_view(), name='nuestrasMarcas'),
    path('tiposDeCoche', views.tiposDeCoche.as_view(), name='tiposDeCoche'),
    path('quienesSomos', views.quienesSomos.as_view(), name='quienesSomos'),
    
    path('change_password/', views.change_password, name='change_password'),

    url(r'^register/$',views.register,name='register'),

    url(r'^user_login/$',views.user_login,name='user_login'),
    
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('', include(router.urls))
    ]

outletCar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from appOutletCar import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('appOutletCar.urls')),
    #url(r'^$',views.index,name='index'),
    #url(r'^special/',views.special,name='special'),
    #url(r'^appOutletCar/',include('appOutletCar.urls')),
    #url(r'^logout/$', views.user_logout, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

appOutletCar/models.py
from django.db import models
from django.db.models import Model
from django.contrib.auth.models import User


# Create your models here.
class Lugar(models.Model):
    cod_ciudad = models.CharField(null=False, primary_key=True, max_length=4)
    ciudad = models.CharField(max_length=100)
    provincia = models.CharField(max_length=100)

    def __str__(self):

        return self.cod_ciudad


class Marca(models.Model):
    nombre_Marca = models.CharField(max_length=100, null=False, primary_key=True)
    descripcion = models.CharField(max_length=5000)
    fecha_creacion = models.DateField()

    def __str__(self):

        return self.nombre_Marca


class Modelo(models.Model):
    nombre_Modelo = models.CharField(max_length=100, null=False, primary_key=True)
    categoria = models.CharField(max_length=100)
    traccion = models.IntegerField()
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)

    def __str__(self):

        return self.nombre_Modelo

class Usuario(models.Model):
    correo = models.CharField(max_length=100, null=False, primary_key=True)
    nombre_usuario = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    telefono = models.IntegerField()
    contrasenya = models.CharField(max_length=100)

    def __str__(self):

        return self.correo


class Coche(models.Model):
    n_bastidor = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    anyo = models.IntegerField()
    n_km = models.IntegerField()
    combustible = models.CharField(max_length=100)
    potencia = models.IntegerField()
    precio = models.FloatField()
    cambio = models.CharField(max_length=100)
    consumo = models.FloatField()
    comentario = models.CharField(max_length=1000)
    modelo = models.ForeignKey(Modelo, on_delete=models.CASCADE)
    lugar = models.ForeignKey(Lugar, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    estado=models.CharField(max_length=100)
    def __str__(self):
        return self.n_bastidor


class FotoCoche(models.Model):
    coche = models.ForeignKey(Coche, on_delete=models.CASCADE)
    fotoCoche = models.ImageField(upload_to='images/', default='images/None/no-img.jpg')
    
    def __str__(self):
        return self.coche.n_bastidor+ " Imagen"



class Comment(models.Model):
    coche = models.ForeignKey(Coche,on_delete=models.CASCADE,related_name='comments')
    usuario= models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.usuario)

class TipoDeCoche(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=2000)

    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return self.nombre

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
        return self.user.username
    

appOutletCar/forms.py
from .models import Comment, FotoCoche
from django import forms
from appOutletCar.models import UserProfileInfo
from django.contrib.auth.models import User
from .models import Coche

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', )
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')    
    class Meta:
        model = FotoCoche
        fields = ('image', )
        
class cocheForm(forms.ModelForm):

    class Meta:
        model = Coche
        fields = ('usuario', 'modelo', 'anyo','estado', 'n_bastidor','color', 'n_km','combustible', 'potencia','precio', 'cambio','consumo', 'comentario','lugar')

appOutletCar/templates/EditarUsuario.html
{% extends 'base.html' %}{% load static %}{% load bootstrap %}
{% block title %}Datos de Usuario{% endblock title %}
{% block contenido %}
{% block css %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/base-min.css">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-min.css">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css">
    <link rel="stylesheet" href="{% static 'css/layouts/pricing.css' %}">
{% endblock css %}

<h2>Edita tus datos</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>
{% endblock contenido %}

appOutletCar/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A layout example that shows off a blog page with a list of posts.">    
    <title>{% block titulo %}outletCar{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block css %}    
            <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
            <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/base-min.css">
            <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-min.css">
            <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% load static %}
        <link rel="stylesheet" href="{% static 'css/layouts/gallery.css' %}">
    {% endblock %}
    {% block javascript %}
    
    {% endblock %}

</head>
<body>
    <div class="header">
        <div class="pure-menu pure-menu-horizontal">
            <a class="pure-menu-heading" href="{% url 'appOutletCar:home'%}">OUTLET CAR</a>

            <ul class="pure-menu-list">
                {% load i18n %}
                <li class="pure-menu-item pure-menu-selected"><a href="{% url 'appOutletCar:quienesSomos'%}" class="pure-menu-link">{% trans "QUIENES SOMOS" %}</a></li>
                <li class="pure-menu-item pure-menu-selected"><a href="{% url 'appOutletCar:tiposDeCoche'%}" class="pure-menu-link">{% trans "TIPOS DE COCHE" %}</a></li>
                <li class="pure-menu-item pure-menu-selected"><a href="{% url 'appOutletCar:nuestrasMarcas'%}" class="pure-menu-link">{% trans "NUESTRAS MARCAS" %}</a></li>
                
		{% if user.is_authenticated %}
                {% load i18n %}
			<li class="pure-menu-item pure-menu-selected"><a href="{% url 'appOutletCar:añadirCoche'%}" class="pure-menu-link">{% trans "AÑADIR COCHE" %}</a></li>
                	{% trans "HOLA " %}{{ user.username }}! <a  class="logout" href="{% url 'logout' %}">  {% trans "Cerrar sesión " %}</a>
                {% else %}
                	<li class="pure-menu-item"><a href="{% url 'login' %}" class="pure menu-link" >{% trans "INICIO SESION" %}</a></li>
                	<li class="pure-menu-item"><a href="{% url 'appOutletCar:signup'%}" class="pure menu-link" class="sesion">{% trans "REGISTRATE" %}</a></li>
                {% endif %}
        {% if user.is_superuser %}
        <li class="pure-menu-item pure-menu-selected"><a href="{% url 'appOutletCar:cochess'%}" class="pure-menu-link">{% trans "ADMIN" %}</a></li>
        {% endif %}
            </ul>
        </div>
    </div>
    
    {% block contenido %}
        
    {% endblock contenido %}
    <div class="footer">
        {% if user.is_authenticated %}
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <div id="app1"> 
            <input v-model="count" :readonly="true"></input>
            <button v-on:click="count++" @click="persist">Like</button>
        </div>
        <script type="text/javascript">
            const app1 = new Vue({
            el:'#app1',
            data: {
                count:0,
            },
            mounted() {
                if(localStorage.count) this.count = localStorage.count;
            },
            methods: {
                persist() {
                localStorage.count = this.count;
                }
            }
            })
        </script>
         {%else%}
         <a href="{% url 'login'%}" class="btn btn-primary  btn-lg">Iniciar sesion</a>
     {% endif %}





        <div class="pure-menu pure-menu-horizontal">
            <ul>
                <li class="pure-menu-item"><a href="https://www.facebook.com/OutletCar-104406484393552/?modal=admin_todo_tour" class="link">  Facebook  </a></li>
                <li class="pure-menu-item"><a href="http://twitter.com/yuilibrary/" class="link">  Twitter  </a></li>
                <li class="pure-menu-item"><a href="https://github.com/JorgeLeku/outletCar2.0" class="link">  GitHub  </a></li>
		    
		{% csrf_token %}
		<input name="next" type="hidden" value="{{ redirect_to }}" />
		<select name="language">
			{% get_current_language as LANGUAGE_CODE %}
			{% get_available_languages as LANGUAGES %}
			{% for lang in LANGUAGES %}
			<option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected"{% endif %}>
				{{ lang.1 }} ({{ lang.0 }})
			</option>
			{% endfor %}
		</select>
		<input type="submit" value="Go" />

            </ul>
        </div>
    </div>
    <script>$(document).ready(function(){
        $("a.link").click(function(evento){     
        if(confirm("Se le redirigirá a otra pagina. ¿Desea continuar?")){
        $("#delete-button").attr("href", "query.php?ACTION=delete&ID='1'");
    }
    else{
        return false;
    }
    });
  });
  
  </script>
</body>


<script>$(document).ready(function(){
    $("a.logout").click(function(evento){     
        if(confirm("¿Está seguro de que desea cerrar sesión?")){
        $("#delete-button").attr("href", "query.php?ACTION=delete&ID='1'");
    }
    else{
        return false;
    }
    });
  });
  
  </script>
</html>

appOutletCar/templates/cochesNuevos.html
{% extends 'base.html' %}{% block contenido %}{% load static %}{% load bootstrap %}

{% block css %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/base-min.css">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-min.css">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css">
    <link rel="stylesheet" href="{% static 'css/layouts/pricing.css' %}">
{% endblock css %}
<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header-sidebar">
            <h1 class="brand-title" >BUSCA</h1>
            <h2 class="brand-tagline">EL COCHE A TU MEDIDA</h2>
            
            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <form class="form" method="GET">
                            {{filter.form|bootstrap}}
                        <button class="pure-button" type="submit" >BUSCAR</button>
                        </form>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>
<div class="content pure-u-1 pure-u-md-3-4">
    <div class="pricing-tables pure-g">
        {% if filter.qs %}
            {% for coche in filter.qs %}
            {% if coche.estado == 'Nuevo' %}
                <div class="pure-u-1 pure-u-md-1">
                    <div class="pricing-table pricing-table-free">
                        <div class="pricing-table-header">
                            <h2>{{ coche.modelo.marca.nombre_Marca }}</h2>
                            <span class="pricing-table-price">
                                {{coche.modelo}}    <span>{{coche.precio}}</span>
                            </span>
                            
                        </div>

                        <ul class="pricing-table-list">
                            <li>año: {{coche.anyo}}</li>
                            <li>KM: {{coche.n_km}}</li>
                            <li>Combustible: {{coche.combustible}}</li>
                            <li>Cambio: {{coche.cambio}}</li>
                            <li>Consumo: {{coche.consumo}}</li>
                            <li>Lugar: {{coche.lugar.ciudad}}, {{coche.lugar.provincia}}</li>
                        </ul>

                        <a class="button-choose pure-button" href="{% url 'appOutletCar:detail' coche.id %}">Choose</a>
                    </div>
                </div>
            {% endif %}
            {% endfor %}
        {% else %}
        <div class="pure-u-1 pure-u-md-1">
                <div class="pricing-table pricing-table-free">
                    <div class="pricing-table-header">
                        <h2>No hay coches</h2>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock contenido %}
    

appOutletCar/templates/cochesSegundaMano.html
{% extends 'base.html' %}{% load static %}{% load bootstrap %}
{% block title %}Lista Coche{% endblock title %}
{% block contenido %}
{% block css %}
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/base-min.css">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-min.css">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css">
    <link rel="stylesheet" href="{% static 'css/layouts/pricing.css' %}">
{% endblock css %}
<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header-sidebar">
            <h1 class="brand-title" >BUSCA</h1>
            <h2 class="brand-tagline">EL COCHE A TU MEDIDA</h2>
            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <form class="form" method="GET">
                            {{filter.form|bootstrap}}
                        <button class="pure-button" type="submit" >BUSCAR</button>
                        </form>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>
<div class="content pure-u-1 pure-u-md-3-4">
    <div class="pricing-tables pure-g">
        
        {% if filter.qs %}
            {% for coche in filter.qs %}
            {% if coche.estado == 'Segunda mano' %}
                <div class="pure-u-1 pure-u-md-1">
                    <div class="pricing-table pricing-table-free">
                        <div class="pricing-table-header">
                            <h2>{{ coche.modelo.marca.nombre_Marca }}</h2>
                            <span class="pricing-table-price">
                                {{coche.modelo}}    <span>{{coche.precio}}</span>
                            </span>
                            
                        </div>

                        <ul class="pricing-table-list">
                            <li>año: {{coche.anyo}}</li>
                            <li>KM: {{coche.n_km}}</li>
                            <li>Combustible: {{coche.combustible}}</li>
                            <li>Cambio: {{coche.cambio}}</li>
                            <li>Consumo: {{coche.consumo}}</li>
                            <li>Lugar: {{coche.lugar.ciudad}}, {{coche.lugar.provincia}}</li>
                        </ul>

                        <a class="button-choose pure-button" href="{% url 'appOutletCar:detail' coche.id %}">Choose</a>
                     </div>
                </div>
            {% endif %}
            {% endfor %}
        {% else %}
        <div class="pure-u-1 pure-u-md-1">
                <div class="pricing-table pricing-table-free">
                    <div class="pricing-table-header">
                        <h2>No hay coches</h2>
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock contenido %}
    

appOutletCar/templates/home.html
{%extends 'base.html'%}

<!--<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A layout example that shows off a responsive photo gallery.">    <title>Photo Gallery &ndash; Layout Examples &ndash; Pure</title>    
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
-->
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
       <!-- <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css">-->
    <!--<![endif]-->
    
    
        <!--[if lte IE 8]>
            <link rel="stylesheet" href="css/layouts/gallery-old-ie.css">
        <![endif]-->
        <!--[if gt IE 8]><!-->
            <!--<link rel="stylesheet" href="../static/css/layouts/gallery.css">-->
        <!--<![endif]-->
</head>

{% block javascript %}
    {% load static %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/effects.js' %}"></script>
    <script src="{% static 'js/jquery.qtip-1.0.0-rc3.min.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
{% endblock %}

<script type="text/javascript">
    $(document).ready(function(){
        alert("jQuery cargado correctamente");
    })
</script>

{% block contenido %}


<div>
    <div class="pure-g">
        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1">
            <a href="{% url 'appOutletCar:listaCochesSegunda'%}">
                <img src="../static/img/segundaMano.jpg"
                     alt="Beach">
            </a>

            <aside class="photo-box-caption">
                <span>COCHES DE<br/><a href="{% url 'appOutletCar:listaCochesSegunda'%}">SEGUNDA MANO</a></span>
            </aside>
        </div>

        <!--<div class="text-box pure-u-1 pure-u-md-1-2 pure-u-lg-2-3">
            <div class="l-box">
                <h1 class="text-box-head">Photos from around the world</h1>
                <p class="text-box-subhead">A collection of beautiful photos gathered from Unsplash.com.</p>
            </div>
        </div>-->

        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
            <a href="{% url 'appOutletCar:listaCocheskm0' %}">
                <img src="../static/img/vendido.jpeg"
                     alt="Meadow">
            </a>

            <aside class="photo-box-caption">
                <span>
                    COCHES <br/> <a href="{% url 'appOutletCar:listaCocheskm0' %}">KM 0</a>
                </span>
            </aside>
        </div>

        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
            <a href="{% url 'appOutletCar:listaCochesNuevos'%}">
                <img src="../static/img/cochesNuevos.jpg"
                     alt="City">
            </a>

            <aside class="photo-box-caption">
                <span>
                    NUEVOS <br/><a href="{% url 'appOutletCar:listaCochesNuevos'%}">COCHES</a>
                </span>
            </aside>
        </div>

        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
            <a href="{% url 'appOutletCar:nuestrasMarcas'%}">
                <img src="../static/img/marcas.jpg"
                     alt="Flowers">
            </a>

            <aside class="photo-box-caption">
                <span>
                    MARCAS <br/><a href="{% url 'appOutletCar:nuestrasMarcas'%}">CON LAS QUE TRABAJAMOS</a>
                </span>
            </aside>
        </div>

        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
            <a href="{% url 'appOutletCar:tiposDeCoche'%}">
                <img src="../static/img/tiposDeCoche.jpg"
                     alt="Bridge">
            </a>

            <aside class="photo-box-caption">
                <span>
                    TIPOS<br/><a href="{% url 'appOutletCar:tiposDeCoche'%}">DE COCHE</a>
                </span>
            </aside>
        </div>

        <div class="photo-box photo-box-thin pure-u-1 pure-u-lg-1-3">
            <a href="{% url 'appOutletCar:quienesSomos'%}">
                <img src="../static/img/quienesSomos.jpg"
                     alt="Balloons">
            </a>

            <aside class="photo-box-caption">
                <span>
                    QUIENES<br/><a href="{% url 'appOutletCar:quienesSomos'%}">SOMOS</a>
                </span>
            </aside>
        </div>
    </div>
</div>



{% endblock contenido %}

appOutletCar/templates/index.html
{%extends 'base.html'%}

<!--<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A layout example that shows off a responsive photo gallery.">    <title>Photo Gallery &ndash; Layout Examples &ndash; Pure</title>    
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
-->
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
       <!-- <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/grids-responsive-min.css">-->
    <!--<![endif]-->
    
    
        <!--[if lte IE 8]>
            <link rel="stylesheet" href="css/layouts/gallery-old-ie.css">
        <![endif]-->
        <!--[if gt IE 8]><!-->
            <!--<link rel="stylesheet" href="../static/css/layouts/gallery.css">-->
        <!--<![endif]-->
</head>

{% block contenido %}
    



<div>
    <div class="pure-g">
        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1">
            <a href="{% url 'appOutletCar:listaCochesSegunda'%}">
                <img src="../static/img/segundaMano.jpg"
                     alt="Beach">
            </a>

            <aside class="photo-box-caption">
                <span>COCHES DE<br/><a href="{% url 'appOutletCar:listaCochesSegunda'%}">SEGUNDA MANO</a></span>
            </aside>
        </div>

        <!--<div class="text-box pure-u-1 pure-u-md-1-2 pure-u-lg-2-3">
            <div class="l-box">
                <h1 class="text-box-head">Photos from around the world</h1>
                <p class="text-box-subhead">A collection of beautiful photos gathered from Unsplash.com.</p>
            </div>
        </div>-->

        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
            <a href="{% url 'appOutletCar:listaCocheskm0' %}">
                <img src="../static/img/vendido.jpeg"
                     alt="Meadow">
            </a>

            <aside class="photo-box-caption">
                <span>
                    COCHES <br/> <a href="{% url 'appOutletCar:listaCocheskm0' %}">KM 0</a>
                </span>
            </aside>
        </div>

        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
            <a href="{% url 'appOutletCar:listaCochesNuevos'%}">
                <img src="../static/img/cochesNuevos.jpg"
                     alt="City">
            </a>

            <aside class="photo-box-caption">
                <span>
                    NUEVOS <br/><a href="{% url 'appOutletCar:listaCochesNuevos'%}">COCHES</a>
                </span>
            </aside>
        </div>

        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
            <a href="{% url 'appOutletCar:nuestrasMarcas'%}">
                <img src="../static/img/marcas.jpg"
                     alt="Flowers">
            </a>

            <aside class="photo-box-caption">
                <span>
                    MARCAS <br/><a href="{% url 'appOutletCar:nuestrasMarcas'%}">CON LAS QUE TRABAJAMOS</a>
                </span>
            </aside>
        </div>

        <div class="photo-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
            <a href="{% url 'appOutletCar:tiposDeCoche'%}">
                <img src="../static/img/tiposDeCoche.jpg"
                     alt="Bridge">
            </a>

            <aside class="photo-box-caption">
                <span>
                    TIPOS<br/><a href="{% url 'appOutletCar:tiposDeCoche'%}">DE COCHE</a>
                </span>
            </aside>
        </div>

        <div class="photo-box photo-box-thin pure-u-1 pure-u-lg-1-3">
            <a href="{% url 'appOutletCar:quienesSomos'%}">
                <img src="../static/img/quienesSomos.jpg"
                     alt="Balloons">
            </a>

            <aside class="photo-box-caption">
                <span>
                    QUIENES<br/><a href="{% url 'appOutletCar:quienesSomos'%}">SOMOS</a>
                </span>
            </aside>
        </div>
    </div>
</div>



{% endblock contenido %}